# Site settings
title: iffy can
author: Matt Haggard
email: haggardii@gmail.com
description: >
    This is Matt Haggard's personal website.
    I'm a dad, who studied Electrical Engineering and
    programs for a living.  I'm a <a href="http://www.lds.org">Mormon</a> and
    some people call my Iffy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.iffycan.com" # the base hostname & protocol for your site
twitter_username: iffycan
github_username:  iffy

# Build settings
markdown: kramdown
